[package]
name = "s3tui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.17.0"
crossterm = "0.23.0"
rusoto_core = "0.47.0"
rusoto_s3 = "0.47.0"
tokio = "1.16.1"
tokio-stream = "0.1.8"
async-trait = "0.1.52"
chrono = "0.4.19"